---
# tasks file for mediafellows.graylog

- name: Download Graylog Repo Deb
  ansible.builtin.get_url:
    url: "https://packages.graylog2.org/repo/packages/graylog-{{graylog_major_version}}-repository_latest.deb"
    dest: /root/graylog-repo.deb
    force: yes

- name: Ensure other repos debs are uninstalled (might fail if none are found)
  ansible.builtin.shell:
    cmd: "apt remove -y '^graylog-.+-repository'"
  ignore_errors: true

- name: Install Graylog Repo
  ansible.builtin.apt:
    deb: /root/graylog-repo.deb
    state: present

- name: Setup MongoDB repo key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Output Ubuntu release name
  ansible.builtin.debug:
    var: ansible_distribution_release

- name: Setup MongoDB repo
  ansible.builtin.apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/6.0 multiverse"
    state: present

- name: Install MongoDB (needed as Graylog settings DB)
  ansible.builtin.apt:
    name: mongodb-org
    state: latest
    update_cache: yes
  notify: restart mongodb

- name: Enable mongodb server on boot
  ansible.builtin.service:
    name: mongod
    enabled: yes

- name: Install Graylog server
  ansible.builtin.apt:
    name: graylog-server
    state: latest
  notify: restart graylog-server

- name: Add Graylog server config for versions < 3
  ansible.builtin.template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
  when: graylog_major_version is version('3.0', '<')
  notify: restart graylog-server

- name: Add Graylog server config for versions >= 3
  ansible.builtin.template:
    src: server-3.conf.j2
    dest: /etc/graylog/server/server.conf
  when: graylog_major_version is version('3.0', '>=')
  notify: restart graylog-server

- name: Copy graylog extra plugins into plugin dir to be loaded on graylog start
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ graylog_plugin_dir }}/"
  with_items: "{{ graylog_custom_plugins }}"
  notify: restart graylog-server

- name: Enable graylog-server on boot
  ansible.builtin.service:
    name: graylog-server
    enabled: yes
