---
# tasks file for mediafellows.graylog

- name: Download Graylog Repo Deb
  ansible.builtin.get_url:
    url: "https://packages.graylog2.org/repo/packages/graylog-{{graylog_major_version}}-repository_latest.deb"
    dest: /root/graylog-repo.deb
    force: yes

- name: Ensure other repos debs are uninstalled
  ansible.builtin.shell:
    cmd: "apt remove -y '^graylog-.+-repository'"

- name: Install Graylog Repo
  ansible.builtin.apt:
    deb: /root/graylog-repo.deb
    state: present

- name: Install MongoDB (needed as Graylog settings DB)
  ansible.builtin.apt:
    name: mongodb
    state: latest
    update_cache: yes
  notify: restart mongodb

- name: Install Graylog server
  ansible.builtin.apt:
    name: graylog-server
    state: latest
  notify: restart graylog-server

- name: Add Graylog server config for versions < 3
  ansible.builtin.template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
  when: graylog_major_version is version('3.0', '<')
  notify: restart graylog-server

- name: Add Graylog server config for versions >= 3
  ansible.builtin.template:
    src: server-3.conf.j2
    dest: /etc/graylog/server/server.conf
  when: graylog_major_version is version('3.0', '>=')
  notify: restart graylog-server

- name: Copy graylog extra plugins into plugin dir to be loaded on graylog start
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ graylog_plugin_dir }}/"
  with_items: "{{ graylog_custom_plugins }}"
  notify: restart graylog-server

- name: Enable graylog-server on boot
  ansible.builtin.service:
    name: graylog-server
    enabled: yes
