---
# tasks file for mediapeers.graylog

- name: Download Graylog Repo Deb
  get_url:
    url: "https://packages.graylog2.org/repo/packages/graylog-{{graylog_major_version}}-repository_latest.deb"
    dest: /root/graylog-repo.deb
    force: yes

- name: Install Graylog Repo
  apt:
    deb: /root/graylog-repo.deb
    state: present

- name: Install MongoDB and Graylog packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - mongodb
    - graylog-server

- name: Add Graylog server config
  template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
  notify: restart graylog-server

- name: Copy graylog extra plugins into plugin dir to be loaded on graylog start
  get_url:
    url: "{{ item }}"
    dest: "{{ graylog_plugin_dir }}/"
  with_items: "{{ graylog_custom_plugins }}"
  notify: restart graylog-server

- name: Enable graylog-server on boot
  service:
    name: graylog-server
    enabled: yes
