---
# handlers file for mediafellows.graylog

- name: restart graylog-server
  ansible.builtin.service:
    name: graylog-server
    state: restarted

- name: stop graylog-server
  ansible.builtin.service:
    name: graylog-server
    state: stopped

- name: start graylog-server
  ansible.builtin.service:
    name: graylog-server
    state: stopped

- name: restart mongodb
  ansible.builtin.service:
    name: mongodb
    state: restarted
