---
# handlers file for mediafellows.graylog

- name: restart graylog-server
  service:
    name: graylog-server
    state: restarted

- name: stop graylog-server
  service:
    name: graylog-server
    state: stopped

- name: start graylog-server
  service:
    name: graylog-server
    state: stopped

- name: restart mongodb
  service:
    name: mongodb
    state: restarted
